### ISSUE TITLE
sms mms, check for invalid datetime

### ISSUE THREAD

**Issue by lduboeuf** [ubports/telepathy-ofono#13]
As relying on the sms/mms sent time seems not reliable https://gitlab.com/ubports/community-ports/pinephone/-/issues/165

We should check for date validity here and replace sentime with the received one if anything wrong

**Comment by Flohack74** [comment]
Isnt that already fixed with #14 ?

**Comment by lduboeuf** [comment]
not sure if fixed for the pinephone

**Comment by gber** [comment]
Migrated to https://gitlab.com/ubports/development/core/telepathy-ofono/-/issues/13
