### ISSUE TITLE
Unable to send MMS

### ISSUE THREAD

**Issue by rubencarneiro** [ubports/telepathy-ofono#29]
This was tested on Redmi Note 8 Pro Halium 10
- tried to send mms result failed to send all  APN settings is correct, but still wont send.

**Comment by Flohack74** [comment]
@lduboeuf maybe

**Comment by lduboeuf** [comment]
> This was tested on Redmi Note 8 Pro Halium 10
> 
> * tried to send mms result failed to send all  APN settings is correct, but still wont send.

nuntium logs should give you some infos

**Comment by rubencarneiro** [comment]
> 

i will get the logs

**Comment by rubencarneiro** [comment]
![screenshot20220105_212940027](https://user-images.githubusercontent.com/40370995/148292553-fbf42e66-e217-4355-a52e-25b18550f54c.png)

**Comment by lduboeuf** [comment]
so sosomething  to do with ofono. But i don't think it is related to the new feature.

**Comment by rubencarneiro** [comment]
i worked before no it dont, theres recent changes to ofono?

**Comment by rubencarneiro** [comment]
Ofono-setup says:
Android SDK version 27 or greater detected. No modem detection will be made

**Comment by lduboeuf** [comment]
out of my skill sorry

**Comment by gber** [comment]
Migrated to https://gitlab.com/ubports/development/core/telepathy-ofono/-/issues/29
