### ISSUE TITLE
When cellular data is disabled, mms is lost, no notification

### ISSUE THREAD

**Issue by lduboeuf** [ubports/telepathy-ofono#9]
As a reference: https://github.com/ubports/ubuntu-touch/issues/239
Sorry for this old feature request, but who know if any skilled developer can take this ;-) , would be so thanksfull

How hard would it be to send a notification  with a link to download the mms, or for a quick fix, just be notified someone have tried to send a mms ?

**Comment by lduboeuf** [comment]
https://github.com/ubports/nuntium/issues/1

**Comment by gber** [comment]
Migrated to https://gitlab.com/ubports/development/core/telepathy-ofono/-/issues/9
